// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Company struct {
	ID        int    `json:"ID"`
	Name      string `json:"name"`
	Location  string `json:"location"`
	CompanyID int    `json:"companyId"`
	Jobs      []*Job `json:"jobs,omitempty"`
}

type Job struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	CompanyID   int    `json:"companyId"`
}

type NewCompany struct {
	Name      string `json:"name"`
	Location  string `json:"location"`
	CompanyID int    `json:"CompanyId"`
}

type NewJob struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	CompanyID   int    `json:"companyId"`
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"Password"`
}

type Users struct {
	ID       int    `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"Password"`
}
